from library_oop import Book, Member, Library

lib = Library()
lib.add_book(1, "Python 101", "John", 2)
lib.add_book(2, "C++ Basics", "Jane", 1)
lib.add_member(10, "Alice", "alice@mail.com")
lib.add_member(20, "Bob", "bob@mail.com")
print(lib.borrow_book(10, 1))
print(lib.borrow_book(10, 2))
print(lib.borrow_book(10, 1))
print(lib.borrow_book(10, 1))
lib.show_books()
lib.show_member_books(10)
print(lib.return_book(10, 1))
print(lib.return_book(10, 2))
print(lib.return_book(10, 2))
print(lib.borrow_book(999, 1))
print(lib.borrow_book(10, 999))
lib.show_books()
lib.show_member_books(10)
